title: Tuan Plus
description: The personal blog of StormX
url: https://ngzhio.github.io
author: Tuan Do
avatar: /avatar.jpg
email: ssa@gmail.com
location: VN
timezone: +0000

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jemoji

google_analytics: UA-163113883-1

disqus: ngzhio

include:
  - _pages

exclude:
  - scripts/
  - README.md

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      author: "Tuan Plus"
      image: "avatar.jpg"
      share: true
  - scope:
      path: ""      
      type: "pages"
    values:
      layout: "page"
      author: "Tuan Plus"
      image: "avatar.jpg"

# Jekyll Remote Theme
# ===================
remote_theme: ngzhio/jekyll-theme-hamilton

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: avatar.jpg
social:
  name: Shangzhi Huang
  links:
    - https://twitter.com/ngzhio
    - https://github.com/ngzhio
lang: en

# Jekyll Paginate
# ===============
paginate: 10
